# Generated by Django 5.2 on 2025-10-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgnew',
            name='main',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
