# Generated by Django 5.2 on 2025-10-02 23:10

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='rotina', variations={'thumb': {'crop': True, 'height': 32, 'width': 32}})),
            ],
            options={
                'verbose_name': 'Rotina de Trabalho',
                'verbose_name_plural': 'Rotinas de Trabalho',
            },
        ),
    ]
